# Generated by Django 3.2.5 on 2021-08-25 12:25

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_images')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('date_birth', models.DateField()),
                ('ethnicity', models.CharField(choices=[('Black', 'Black'), ('White', 'White'), ('Coloured', 'Coloured'), ('Indian', 'Indian'), ('Chinese', 'Chinese')], default='Black', max_length=200)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=100)),
                ('marital_status', models.CharField(choices=[('Married', 'Married'), ('Single', 'Single'), ('Widowed', 'Widowed'), ('Divorced', 'Divorced')], default='Single', max_length=100)),
                ('addressLine1', models.CharField(blank=True, max_length=100, null=True)),
                ('addressLine2', models.CharField(blank=True, max_length=100, null=True)),
                ('suburb', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(choices=[('Gauteng', 'Gauteng'), ('Mpumalanga', 'Mpumalanga'), ('Free-state', 'Free-state'), ('North-west', 'North-west'), ('Limpopo', 'Limpopo'), ('Western-cape', 'Western-cape'), ('Northern-cape', 'Northern-cape'), ('Estern-cape', 'Estern-cape'), ('Kwazulu-natal', 'Kwazulu-natal')], default='Gauteng', max_length=200)),
                ('phonenumber', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('cover_letter', models.FileField(blank=True, null=True, upload_to='resumes')),
                ('cv', models.FileField(blank=True, null=True, upload_to='resumes')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('position', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), size=None)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(blank=True, max_length=200, null=True)),
                ('qualification', models.CharField(blank=True, max_length=200, null=True)),
                ('level', models.CharField(choices=[('NQF 5 - Certificate', 'NQF 5 - Certificate'), ('NQF 5 - Higher Certificate', 'NQF 5 - Higher Certificate'), ('NQF 5 - First Diploma', 'NQF 5 - First Diploma'), ('NQF 6 - Bachelors Degree', 'NQF 6 - Bachelors Degree'), ('NQF 6 - Professional First Degree Postgraduate', 'NQF 6 - Professional First Degree Postgraduate'), ('NQF 6 - General First Degree', 'NQF 6 - General First Degree'), ('NQF 7 - Postgraduate Diploma', 'NQF 7 - Postgraduate Diploma'), ('NQF 7 - Honours Degree', 'NQF 7 - Honours Degree'), ('NQF 7 - Masters Degree', 'NQF 7 - Masters Degree'), ('NQF 8 - Doctors Degree', 'NQF 8 - Doctors Degree')], default='NQF 5 - Certificate', max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('graduated', models.DateField(blank=True, null=True)),
                ('major_subject', models.CharField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.resume')),
            ],
        ),
    ]
