# Generated by Django 3.0 on 2021-09-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210906_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='ethnicity',
            field=models.CharField(choices=[('Black', 'Black'), ('White', 'White'), ('Coloured', 'Coloured'), ('Indian', 'Indian'), ('Chinese', 'Chinese'), ('Other', 'Other')], default='Black', max_length=200),
        ),
        migrations.AlterField(
            model_name='resume',
            name='province',
            field=models.CharField(choices=[('India', 'India'), (' Singapore', ' Singapore'), (' Hong-Kong', ' Hong-Kong'), ('United_Arab_Emirates', ' United_Arab_Emirates'), ('Limpopo', 'Limpopo'), ('Western-cape', 'Western-cape'), ('Northern-cape', 'Northern-cape'), ('Estern-cape', 'Estern-cape'), ('Kwazulu-natal', 'Kwazulu-natal'), ('Usa', 'Usa'), ('Other', 'Other')], default='India', max_length=200),
        ),
    ]
