# Generated by Django 3.0 on 2021-09-24 09:22

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('categoryImage', models.ImageField(default='category.png', upload_to='media')),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('seoDescription', models.CharField(blank=True, max_length=500, null=True)),
                ('seoKeywords', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('companyLogo', models.ImageField(default='default.png', upload_to='media')),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('seoDescription', models.CharField(blank=True, max_length=500, null=True)),
                ('seoKeywords', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('location', models.CharField(blank=True, max_length=1000, null=True)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('job_type', models.CharField(choices=[('FT', 'Full Time'), ('PT', 'Part Time'), ('RT', 'Remote')], max_length=100)),
                ('salary', models.CharField(blank=True, max_length=30, null=True)),
                ('company_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('experience', models.CharField(choices=[('t1', 'Less than 2 yrs'), ('t2', '2yrs - 5yrs'), ('t3', '5yrs - 10yrs'), ('t4', '10yrs - 15yrs'), ('t5', 'More than 15 yrs')], max_length=100)),
                ('summary', models.TextField(blank=True, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('duties', models.TextField(blank=True, null=True)),
                ('enquiries', models.TextField(blank=True, null=True)),
                ('applications', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('date_posted', models.DateField(blank=True, null=True)),
                ('valid_until', models.CharField(blank=True, max_length=100, null=True)),
                ('contract_type', models.CharField(blank=True, max_length=1000, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(blank=True, max_length=1000, null=True, unique=True)),
                ('seoDescription', models.CharField(blank=True, max_length=1000, null=True)),
                ('seoKeywords', models.CharField(blank=True, max_length=1000, null=True)),
                ('urlLink', models.CharField(blank=True, max_length=1000, null=True)),
                ('last_date', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(blank=True, default=False, null=True)),
                ('is_closed', models.BooleanField(blank=True, default=False, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.Category')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.Company')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
